### PR TITLE
data management

### PR DESCRIPTION
**Pull request by zeinab-mk**
included json samples for data management

### CODE REVIEW

**Review by tayganr — CHANGES_REQUESTED** [review]
**Requested Changes** 

- [ ] Remove **__init__.py**
- [ ] Create a sub-folder beneath **purviewcli/samples/json** (e.g. esa)
- [ ] Move JSON files to new directory
- [ ] Rename JSON files (all lowercase, underscore for spaces)
- [ ] Review SQL DB sources as they appear to have duplicate names (data-lz-sources.json and data-integration-lz-sources.json)
- [ ] Review Collections (e.g. Sales appears twice, Management found once, not sure if that is expected)

**Comment**
I will update the sources.ipynb notebook to include an example that can loop through an array of sources. This can be used as a reference.

**Comment by tayganr** [comment]
@zeinab-mk  Sample notebook for has been updated, demonstrating how to create multiple sources when reading a JSON document with an array. https://github.com/tayganr/purviewcli/blob/master/samples/notebooks%20(plus)/sources.ipynb

**Comment by zeinab-mk** [comment]
moved json files to sample folder. updated json files based on data products scenarios.

**Comment by tayganr** [comment]
@zeinab-mk

- Can you please remove **__init__.py**, this file is not needed as it sits within the samples directory.
- Please refer to the snippet below, analysing the JSON documents shows the AzureSqlDatabase sources are duplicates (i.e. same data source name). If the intention is to create two distinct sources, they will require unique names.
- Lastly, JSON documents with the prefix **data_product_** contain references to the Contoso-Sales collection and therefore have a dependency on that object pre-existing. Not sure if this is intended?

image

**Pull request merged**
